import { Location } from "../../../../@types/Location/Location";
import { DataTypeIds } from "../../../../Constants/Ids/DataTypeIds";
import { DeityIds } from "../../../../Constants/Ids/DeityIds";
import { LocationIds } from "../../../../Constants/Ids/LocationIds";
import { NpcIds } from "../../../../Constants/Ids/NpcIds";
import { separator } from "../../../../Style/ts/separator";
import { dataItemToLinkable } from "../../../../Utilities/LinkableString";

const id = LocationIds.Hraclos;

export const Hraclos: Location = {
  id,
  type: DataTypeIds.Location,
  description: [
    `${id} is a 2 mile-high impossible city, older than anyone can remember. Thousands of years ago, the aelfir, strange and beautiful masked humanoids, and the predecessors to
    the Eladrin and the Elves were 'Gifted' the city by Our Lady Of Moonlight, Selemene. For a thousand millenia, the aelfir existed as the world was forming. The city, miles high and formed of Moonstone,
    protected the aelfir from the elements. But eventually, the aelfir's immortal lives were cut short. If the legends are to be believed, the aelfir were cursed with an affliction that caused their immortality to catch up to many of them far faster than it should have.`,
    `The aelfir reacted to this in a number of ways. Some aelfir took themselves on a journey, to attempt to find a place that was unaffected by time. Their pilgrimage wasn't perfect, but was enough to allow them to reproduce again. These would eventually become the Eladrin, the
    fey-touched children of a plane that was bathed in effervescent moonlight; elegant, nonchalant, and fleeting.`,
    `Others took a darker path. These aelfir also journeyed, but to a plane of shadow; a mirror of our plane much like the feywild, but where the feywild is a mirror bathed in the light of our Lady, the Shadowfell is a mirror quenched in the shadow of souls that have become nothing but husks of hatred and evil.
    These elves would become the Shadar-Kai. Some of them would end up serving the Raven Queen herself, while others would walk the Shadowfell endlessly, their rage fuelling them on and twisting them into creatures that would no longer be recogniseable to someone who lives today.`,
    `The aelfir that decided to remain here on Cala Palúrë (The Light Plane) had a choice to make. Would they allow their bodies to wither away; to let their masked faces disperse into a faint stain on the Weave? or would they find another way to sire children?
    They made their choice, and it was a choice that drove many of them deeper into the city, and into the eventual hands of Ishkrah.`,
    ["The Midwives:", `Ishkrah showed the aelfir how to carry young to term, and how to reproduce like themselves; an idea that was alien to the aelfir at the time. The aelfir that helped sire the young and stayed with Ishkrath showed themselves to be loyal. Those who follow this path are known as Ishkrah's Midwives.
    To this day, some rare elves born on ${LocationIds.CryingIsland} carry spiderlike traits – additional limbs and eyes, thick cartilaginous hairs on their forearms and palms, exoskeletal plates, mandibles, and spinnerets.
    These strange elves are treated with a mixture of devotion and fear by their surrounding community, but the majority of them – if they survive gestation and the first few difficult years of their lives – will join the Midwives, an ancient guild devoted to the survival of the elf race, and will join their new family in the lower levels of ${id}.
    The midwives are trained, through meditation and magic, to augment their spider-blood traits until they are truly terrifying to behold. Two extra
    eyes shift into eight, providing uncanny perception; the fingertips and the soles of the feet grow long gripping hairs, allowing them to effortlessly climb sheer surfaces; tough skin hardens to an iridescent carapace; faces distort into furred mandibles, dripping with paralysing venom; arms and legs split
    into multiple limbs; and spinnerets pucker and blossom from abdomens, ready to weave fine webs of glistening silk to trap their prey.
    A true mistress of the art – all midwives are female – can crack and remould their humanoid form into something utterly other, a nightmare mixture of drow and spider, a chittering, towering, arachnid-centaur horror known as a Drider that few can hope to best in combat.
    While dangerous, however, most Midwives treat the locals as friends, and do whatever they can to help them, as they are never hostile to those that ask for help.`],
    ["A city of moonlight:", `Nearly everyone in ${id} worships one of the three major Elvish Pantheon gods - but most worship the Lady of Moonlight, Selemene. Those that do not worship her directly worship either Oko, Elistraee, or sometimes the Raven Queen. The centre of the city is hollow, shining bright sun onto its residents by day, and bathing them
    in moonlight by night.`],
    ["Political Structure:", `Since the end of the second age, after the Elvish Civil War, the city has been under the rule of the Damnou (Council of Three) - These are currently: The Vermissian (${dataItemToLinkable(DataTypeIds.Npc, NpcIds.Acothriass)}), The Mother Midwife (${dataItemToLinkable(DataTypeIds.Npc, NpcIds.ChiltrissIsselde)}), and The High Voice (${dataItemToLinkable(DataTypeIds.Npc, NpcIds.FelaraLunirs)}). The city does, however, have many different factions, or houses, all of which try to attain a modicum of power and status. These houses include:`],
    "House Fol're; a house well known for its trade of books and rare crafted artifacts from distant corners of the globe. This house has, since ~4e 400, lost a lot of its power and wealth, after a number of its members were caught trying to perform a coup of the city, but failed.",
    "House Baerne; a drow-only house originally from Menzoberranzan that are known for their powerful clerical abilities.",
    "House Fin'Telemna; a house known for its wizarding abilities that have sired many of the High Sages of Vermissian over the centuries, and are known for a recognizeable trait of pure silver-shimmering hair.",
    "House N'a'shezbaernon; a house known for its martial prowess.",
    "House Me'larn, House Ken'afin, and House Tuin'Tarl, merchantile houses that trade many things in and out of the city out from the Blue Docks, and deal with a large amount of the city's wealth flow.",
    "House Lun'irs; a house that has sired many high clerics of Elistraee, Selemene and Oko, including three High Voices in the last millenia.",
    "House Is'selde; The 'official' house that the members of The Midwives are allowed to join. This is the only elvish house that is allowed to be joined, rather than born into. All members of house Is'selde are female midwives, and are nearly all drow.",
    ["Rules of the City:", `Slavery is banned in ${id}, being one of Elistraee's tenets that no elf shall hold forced dominion over another. People found with links to slavery are punishable by permanent imprisonment, or public execution.
    Weapons are not allowed to be carried in the city without a permit; The people that are exempt from this are members of the Knights (in the Blue Docks), the Black Guard (an elite protection force known for their recognizeable black heavy armor), and certain higher ranking members of the city such as the Damnou, members of one of the academies, or very well known nobles.
    Punishment for being found with a weapon is initially damage inflicted by that weapon to a person, and confiscation of the weapon, with the severity of punishment increasing per offence.
    ALL public and many private events require Elves to wear Masks to cover their face; an ancient nod to the Aelfir that originally lived in the impossibly tall tower of moonstone that they inhabit now.
    Most high elves in the city, as well as many drow, that are not lower class citizens often wear their mask more often than not, and the most traditional High Elves or Drow never take the mask off once it is worn, going from their 7th birthday (when it is initially crafted and given) to their death hundreds of years later with many of their friends and even their partners having never seen their true faces.
    It is a social crime to not wear your mask to a social events, such as Galas or Parties, and while this particular crime will not be punished by death, doing so may as well be social suicide for any elves that have a name for themselves.
    In all instances of crime that goes beyond minor, non-elves are usually treated with fines, exile, or occasionally public execution, depending on the severity of their crime, but are never imprisoned.`],
    ["The Heart of the City:", "A huge, energetic core of ancient aelfir magic, the Heart is what powers the city. People draw their power from it, use it to light lanterns, start hearthfires, and take the huge glass elevators that run up either side of the Central Shaft of the city to different levels. It also powers the Vermissian, or what became of it anyway. "],
    ["The Vermissian:", `An attempt at creating an easier way of moving round the city by ancient aelfir mages, the Vermissian tunnels are a haunted, semi-phased set of channels that run throughout the city, permeating it. Many of the levels of ${id} are dangerous, due to their
    proximity to the openings of the Vermissian. Vermissian Sages, the scholars of the Vermissian, attempt to uncover what they can about this wherever possible. Most folk do not enter the Vermissian; it is a place of madness, darkness, and danger.`],
    ["The Vermissian School:", "The place of study of the Vermissian Sages, this school, located near the peak of the spire in New Haven, holds the main library of the city. Entrance to the library is permitted only by written permission of the High Sage of the Vermissian, or if you are a member of the Vermissian Sages. Most People here train as wizards, with the occasional Sorcerer."],
    ["Church of the Sword dancers:", `The clerical school of ${id}, this church is located at the highest point of ${id} - nearly two miles above the surface. It is a small church, holding only around 30 people at most. It trains elite fighters, clerics and Bladesingers, who learn the initial art of wizardry at the Vermissian school and then are taught to weave their magic into song in the high gardens of the ancient Aelfir.`],
    separator,
    ["New Haven (Level 30-31):", `Atop ${id}, ten thousand prayer flags flutter and snap in the screaming winds and red-mawed hyenas prowl the windy levels, ravenous and sacred. This is New Heaven, a place of worship, and a place for the dead, accessible only by a select handful within the city.
    Clustered throughout the district are Carrion Priests - who look after the dead of the city - as well as worshippers of ${DeityIds.Yddragsil}, god of the wind and sky, of weather and lightning. Atop this area, a masked and feathered cult devoted to capturing the winds live,
    a hermitage bristling with copper resonators that buzz and hum when thunder approaches there. It’s said that the oracles of ${DeityIds.Yddragsil} can tell you when it’s going to rain, right down to the second,
    and if pressed they can shift oncoming weather patterns away from ${id} by abjuring them like demons with their mouths full of dirt, and iron bars nailing their feet to the structure of the Spire.
    It’s said that the corvids here have learned to speak, but they only do so in riddles and half-truths, and should never be trusted.
    It’s said that, if one of true faith leaps from the highest point in New Haven and plummets towards the ground with no fear in their heart,
    they’ll be reborn as one of the blue-white doves that cluster around the steps of the holiest temples.`],
    ["Amaranth (Level 29):", `Amaranth was the original home of the aelfir, and it is as strange and beautiful as they were. Great palaces of cold stone reach from the polished marble floor to the glittering, star-studded roof; lush vermillion carpets line the streets, and soft magelight auroras flicker through the air to provide illumination as snow falls from above; servants and messenger-birds flit back and forth through shadowed back alleys,
    flashing identification emblazoned on their bodies to gain access through ranks of black-armoured guards. Aelfir whiled away the hours creating art, perfecting their work of gold, silver, and mithril-smithing, and learning the secrets of the world from dusty tomes.
    They, being creatures of cold lands, utilised miracles and magic on an industrial scale to keep the entire district chilled only a handful of degrees above freezing.
    While they did not feel the cold, and make a habit of wearing as little as possible, many who are not high elves used to this icy area who spend any length of time in the district quickly adopt a variety of heavy robes, scarves and gloves to retain body heat as best they can.`],
    ["The Silver Quarter (Level 28):", `People come to the Silver Quarter to see, and to be seen. A glittering web of interconnected streets and buildings, perpetually illuminated by ancient magelights covered in coloured filters, the Silver Quarter is the destination for the rich and famous within Spire, and from beyond, to spend their hard-earned or easily-inherited cash on parties, luxury goods, expensive apartments and unique pleasures.
      Water is pumped up from the rivers of the north docks, purified, and spread throughout the district via a network of canals that are patrolled and fought over by several rival gangs of boatmen. The boatmen do their best to keep their brawls and skiff-bys out of the public eye, for fear of upsetting paying customers.
      Here, and in Amaranth, nearly all nobles never take off their masks, and parties filled with illicit substances and illegal activities occur night after night, for those with enough coin.`],
    ["The Lunar Basilica (Levels 24-27):", `The Lunar Basilica was the grand seat of the theocratic power of the aelfir – their gods, brought down to ${id} from their cold and ancient homes wanted true devotion, and so they were spared no expense.
    A truly awe-inspiring temple to worship them, the Lunar Basilica has a huge opening that faces west, allowing the Sunlight to filter in during the dawn and the Moonlight to filter in at dusk. The opening is a huge wall of force - many of the Aelfir believed that obscuring the light of their gods with glass was offensive,
    and this is a belief that is carried through to this day within the temple.
    The area is divided up in a horseshoe-like shape, with temples to Oko and Elistraee on the right and left flanking the grand entrance, and a small shrine dedicated to ${DeityIds.Vulkoor}, the elvish god of War, in a small dugout to the left. There is a similar dugout across the horseshoe to the right, although it is empty.
    In the centre of the horseshoe is a dazzling white and gold square dedicated to the Great Selemene, where hordes of pilgrims of all races (although mostly elves) stream back and forth between temples to pay their respects to their gods. The entire place is built of bright white and grey stone, colourful banners to the gods and goddesses hang from walls, sunlight and moonlight shine in from the open roof above.
    The High Voice performs a Sermon every day at dusk here as the moon rises, and many people come to watch.`],
    ["The Perch (Level 23):", `People were never meant to live in Perch. Strapped, nailed and bolted to the outer wall of ${id}, Perch is a patchwork collection of ramshackle and scavenged buildings where those driven out of other communities try their best to make a living. Those who survive more than a month or two are some of the toughest, most resourceful folk in the city – and those born a couple of generations in are exceptional indeed. The buildings must be traversed with either magic, or special climbing equipment, lest you risk your life falling from thousands of feet down onto the muddy ground or frigid blue waters below.`],
    ["Ivory Row (Levels 20-23):", `Once, hundreds of years ago, Ivory Row was a bustling hive of society – the place to see and be seen, when the upper levels were cordoned off only to those aelfir who held high seats within one of the Damnou's circles.
    Ivory row was founded upon the efforts of three long-dead drow ivory magnates, funnelling twisted unicorn-horn and hard-won tygre-tusk to desperate buyers in the home nations. Row upon row of houses, each more expansive and beautiful than the last, stretched out to the district walls, and the streets at night were filled with the sound of soirees and parties running on until the early morning.
    But Ivory Row fell out of fashion, and after the aelfir civil war, the nobles of the city that had decided not to follow the elves that emigrated to what would become ${LocationIds.Menzoberranzan}, instead emigrated to the gaudy and exciting Silver Quarter and, if permitted, Amaranth. So, street by street, Ivory row fell into quiet and slow, gentle decay.
    Now, Ivory Row is a shadow of its former self – those same huge mansions exist, still, but are crumbling and abandoned, all owned by a trio of decrepit and stubborn landlords each unwilling to give the other an ounce of control. Those few surviving who do live here, unable or unwilling to move out, are trapped in a forgotten era of faded glory. Corruption and robberies are rife on these streets, even for an area that is meant be supposedly 'Enlightened'. `],
    ["The High Garden (Levels 5-19):", `${id} is hungry, and the Garden feeds it. Acres upon acres of land are given over to the production of food, the majority of it able to grow without access to natural light: algae, mushrooms, crustaceans, insects, grubs, and so on.  The scant external space there is
    jealously guarded and given over to the production of fruit, which nobles prize and pay a top price for. thanks to the scant policing from the city guard (supplanted, and some might argue replaced, by enforcers hired by the larger farm conglomerates to protect their interests) the habitation in the Garden is an easy place to find a sympathetic contact and a place to lay low for a few days while the fallout from your latest endeavour blows over.`],
    ["The Works (Level 0-4):", `Blacktar smoke clings to every surface in the Works: a network of metal gantries, manufacturing plants and storage houses, lined with workers who, eyes on the floor, shuffle through the smoky streets past chained-together indentured elves hammering on steel. It is here that the wheels of ${id}'s industry turn. Almost every inch is covered in factories or people, crowded and dark and close and toxic
    – spend too long in the Works and you bring up sticky black tar with each cough. The noise is the worst part, though, and often deafening: presses operated by the blood and sweat of elves, the scrape of steel on steel and the staccato howls of rudimentary machinery trying and failing to chug along.
    `],
    ["The Blue Docks (Level 0):", `A sea of flashing blue cloth awaits the traveller on foot, boat, or beast of burden, who arrives in ${id}. In the main docks of the city, known as the blue docks, the merchants and traders dress in blue scarves and robes, and dye their stall awnings the colour of the midsummer sky. Even nobles, who normally eschew bright colours, are wrapped head-to-toe in different shades of blue – from aquamarine to teal to sapphire to navy.
    It’s seen as a mark of pride to have the brightest, or the most unique, shade, and even the lowliest beggar will carry a scrap of indigo rag for luck, as an homage to Oko. The Knights run the Blue Docks. In ages past, the Knightly Order of St Beneferas swore to protect traders, travellers and strangers with their lives, and in recognition of this, the Damnou saw fit to give them dominion over the docks, so they could better serve their people.
    Now, no-one would recognise St Beneferas if he walked down the high street. The Knights are a quarrelling cadre of enforcers, extortionists and brawlers who dress up in gaudy armour, pay too much money for expensive broadswords (that they are legally allowed to carry, thanks to that ancient pact) and like to throw their weight around when it comes to tithe collection, perceived slights against their honour, and contests of “Knightly” virtue.
    `],
    ["Red Row (Level -1):", `A bustling, smoky, fire-lit knot of activity, Red Row attracts the best and worst the undercity has to offer. Criminals rub shoulders with powder-cheeked nobles, filthy gutterkin wait tables, and retroengineers ply their dangerous wares on every street corner.
    Law and order are strange, half-remembered concepts to many of the inhabitants, and while the Guard maintain a token presence down here, much of the day-to-day enforcement is carried out by gangs of armed humans and drow working for one of the three 'bosses' who run the joint.`],
    ["Derelictus (Level -2)", "A mostly abandoned level, Buried in the city bowels, Derelictus is a thrice cursed mess of broken masonry, tunnels to nowhere, and wet runoff from the layers above. Here, the dregs of the populace struggle to survive from day to day, killers stalk the streets, and darkness permeates the area. What little light there is down here is artificial, or carried by the populace, and the entire place is covered in shadows and dirty magic."],
    ["The Heart (Level -3 and below):", `There is a blistering, infectious, otherworldly magic at the centre of ${id}. as though the structure is so alien, so impossible, that the deeper one proceeds within, the less hold reality has over the world. The Heart, deep below ground and nestled within mage-warped tunnels and flickering dead ends, is the dead centre of the structure. Rational time and space – as the rest of the world would know it - are a long-lost memory to the strange things that live there.
    If it is impossible to map the city with any accuracy, it is doubly impossible to map the Heart. Those guides that can be found, huddled in the corners of Derelictus bars staring blankly into their liquor or perched in the ruins of a building on the edge of the Heart, eyes glinting in the dark, ply their trade through intuition, not memory. They feel the space of the Heart the way one would feel the skin of a lover, or warily eye a barking hound, and can smell the routes they’re asked to take.
    Doors and passageways flicker in and out of existence like faulty magelights; corridors constrict and crush trespassers; the floors buckle and undulate, their surface somehow unbreaking.`],
  ],
  population: "~ 100,000 (58% sun-elf, 36% drow, 3% half-elf, 2% humans, 1% other races)",
};
