import { Location } from "../../../../@types/Location/Location";
import { DataTypeIds } from "../../../../Constants/Ids/DataTypeIds";
import { LocationIds } from "../../../../Constants/Ids/LocationIds";

export const Kylvoro: Location = {
  id: LocationIds.Kylvoro,
  type: DataTypeIds.Location,
  description: [
    `Located near the western coast of Misthalin, Kylvoro is a diplomatic hub and fortified stronghold overseeing much of the politics along the coastal regions. The city sits on the edge of the Yama mountain, the largest southern mountain in the Angania Mountains, and lies near the bank of the Bishtou River.
    Kylvoro was set up long ago as a diplomatic outpost by the Monarchy of Misthalin to help govern the western reaches of the kingdom, and facilitate communcation and trade with the Elves of the Crying Island. Elvish noble leaders of Kylvoro often proclaim it to be the 'Capital of the Western Reach', however there is much contention over this statement, which many find to be sheer arrogance on behalf of the Kylvoran nobles.`,
    `With a population of around 1250 Kylvoro is one of the smaller cities of Misthalin. The majority of the Kylvoran population is human, elf, or half-elf.
    Small percentages of gnomes and dwarves also reside in the city, with occasional sightings of rarer races found within adventuring parties or those sent to Kylvoro on diplomatic journeys.
    There were formerly a very healthy population of Tieflings who were originally native to this area and lived in the city but are an extremely rare sight after the infamous Tiefling purge of 164.`,
    `There is much disparity in the wealth of the city with the more impoverished western section becoming less well kept leading to the richer citizens moving across to the eastern sides leading to its eventual gentrification. This has lead to more of the poor, homeless and unlawful taking residence on the west side only exacerbating the situation.
    On the west side there is a few small taverns, meeting halls and small specialist shops for guilds and factions. The Nightlock is a popular shady darkened blue-black wooden tavern common among the rougher and more shady groups, a place where only aliases are used, and gambling and schemes are awry. The area is common to more of the poorer folk and many street urchins lurk around often trying to pickpocket foolish travellers, who stay on this side of town to save gold.
    The few farmhouses outside the walls are responsible for growing the largest proportion of produce for the city, while meat being mostly in the form of fish supplied from the Bishtou river and transported from the west coast. There is the waterfall of Beauregard (named after a founding noble) to the immediate west of the city which hides behind it a ‘small’ mysterious cave that children are told haunting stories of and is strictly off limits to most citizens and travellers. Monsters, treasure, or culty shit to be most likely. `,
    "As of 5e 169, after an attempted coup by Jacob Raskpoplous (noble son of the previous leader and instigator of the Tiefling purge, Jarnn Raskopolous), The Leader of the city (Lorién Kylvoros) is Prince Derendil, the current liason to the Crying Islands.",
    ["City Infrastructure:", `At the base of the mountain is a heavily fortified city wall which wraps around all the houses, market stores, tavern, armoury, stables and infrastructure in the city. Kylvoro’s walls ascend up a kilometre up the mountain with the city being built in to and embracing the slope. Many consider the walls to contain the city of Kylvoro itself, with buildings higher up the mountain and farmhouses on the Bishtou plains outside of the city walls being additional and to be just contained within Kylvoro’s outer limits.
    These walls are lightly guarded with Mistguard, but entry in and out is usually uneventful due to frequent political convoys and trading merchants.`],
    ["City Square:", `As you enter through the main gates you enter in to a large open cobbled piazza. The area is common place where many people will regularly bustle through during their day.
    In the centre stands a 10ft golden statue of King Roald wielding his sword facing the main gates.
    It is placed within a 12ft diameter pond with many water features and a small golden fence around the edge with inscriptions in
    an ancient text that very few even comprehend.
    The piazza is flanked by the main gate to the south, Talem’s many stores on the east, Glady’s Tavern and various divergent pathways to the North and the Kylvoro Armoury, stables and the entrance to the market street to the west.`],
    ["Gladys's Tavern:", `Gladys’ Tavern is the heart and soul of the city and is the focal point for all to meet, drink, and for travellers to stay. It is a large wooden tavern with plenty of room and 'Gladys' in ornate golden letter above the door. Taverns are usually named something descriptive of the local wildlife, something regal, or even humorous, but when you are as popular as Gladys why call it anything else?
    Run by the tall and heavy-set dwarf Gladys Ruane, who sports long curly brown hair and wears the same brown dress and white robe, the tavern is the most popular location for the people of Kylvoro to pass the time. Gladys remembers every name, face and order that comes through the door. With a passion for her work and a love of her city, Gladys is always there with a smile and ready for a chat.
    Many of the common folk look to Gladys as a voice of the people and a strong leader in the community. The tavern is decorated with many ornate paintings, furniture, small unknown relics and hunting trophies of all kinds. There are many board games, and gambling and almost always a bard playing.
    This is the best spot for food in the city with cooking currently undertaken by Venri the Half-Orc, sister to the famous Half-Orc chef J'rath in the castle of Vvardenbridge (Formerly Sous the Tiefling).
    With such great respect for the tavern and for Gladys, no one ever steps out of line with many regarding the tavern as a neutral space for peace, negotiations and relaxation. If anyone wants to fight they can take it outside or to the western side of the city, otherwise Gladys (or anyone else in the tavern) will quickly end the fight for you, before throwing you out the door.`],
    ["Kylvoro Armory:", `The Kylvoro Armoury is run by the dwarf Perceval McKintley. Located a few buildings along from the tavern, the Armoury has a spot right in the centre of the city.
    The armoury looks cobbled together with materials from the various patch jobs over time - Percival cares more about his work than the building he works in.
    If you need weapons or armour there is no better a place to go. Besides the fact that it's the only armoury in a good few days travel, the steel work this one dwarf produces are as fine as that produced by twelve workers, and just as fast too. A dwarf who sticks hard by the good old-fashioned rules and values respect and honesty, he will never drop his prices, but he may give you an extra something if you’re in his good books.
    He always knows a thing or two about the city’s goings on if you ask him nicely due to his confident eyes and ears about the city. His adopted daughter, Kara, tends to the finances for the shop as well as running errands and forging equipment if necessary.`],
    ["Marlin's Stables", `The Stables are small but one of the most well-kept places in the city, many citizens aren’t used to the comforts the horses receive. Marlin the stable hand runs it all by himself and it is his pride and joy. He feels more at home with the horses than actual people and happily spends all his time there. Quite awkward to speak with in person he has a special way with horses and animals that many are amazed by, with him muttering under his breath to the horses throughout his day.
    Marlin is young, lean in stature with a mess of brown hair that gets in his eyes.`],
    ["Stores:", `There is a general store, book store, and a magical goods and alchemy store flanking the entire right side of the main square as one long building. Whilst having separate signs and entrances, they are all run by the same Talem Moxie. He is a tall slender waist coated Tabaxi with a fancy white shirt underneath with the sleeves rolled above his elbows.
    Having a monopoly on all the best stores, he is a charming hustler, who runs between all the stores through their adjoining doors behind the counters, changing his coloured waistcoat for another in each store and his long slicked back hair to match using some magical illusions.
    He is rumoured to have been a street performer turned con-man before coming in to great fortune in his late 30’s and opening his many stores. Whilst the stores often seem like no one is in Talem will rapidly appear through the side door, and don’t think you can swipe anything the place is better defended than the main gate, with various magical traps.
    The magical goods store has many items but many of them are party trick items and faulty overambitious items that Talem has been messing around with to try to sell. Some work, and some don't.`],
    ["Erukteak Monastery:", `On the peak of the Yama mountain lies the ancient Ecruteak monastery, that was built before the city of Kylvoro was founded. The Ecruteak monastery in incredibly hard to access having to pass through the heart of the Yama mountain.
    It is unknown who resides there and what happens inside, anyone who has ever got to the front door has never been granted access inside,
    unless in the upmost importance or direst emergency but with visitors sworn to secrecy. Many tall tales of what lies inside this monastery are told by the people in the city with almost everyone having a different theory. But it’s Monks. Most definitely Monks. 100% Monks.`],
    ["The Cirrus:", `The politicians and nobles are exclusively the high elves, half elves, and the affluent humans from rich and noble lineages. They mostly reside in the royal parliamentary palace of Kylvoro, dubbed ‘The Cirrus’
    due to it sitting two-thirds up the Yama which is level with some of the lower mountain peaks and almost appears to float on the clouds. Many of the disenfranchised commoners living at the base of the Yama mountain simply refer to it instead as ‘The Circus’ with the politicians ‘being better suited as jesters.’
    There has been much distrust and loss of faith in the nobles by the people ever since the Tiefling purge and its extreme condemnation by King Roald. A large political reshuffle and reforms of the laws in Kylvoro, have been implemented in the past five years in response to the outcry.`],
    ["Native Tiefling Settlement:", `Slightly higher up the Yama mountain are the remains of the large native settlement of Tieflings who resided outside of the main city walls. The settlement was torched and burnt during the purge and has become a tragic scar on the mountain. Over recent years many citizens have begun to clean up the area and turn it in to the site of prayer to the gods and remembrance of the Tieflings who lost their lives,
    in the hopes that many can repay their debts and sins and to hope future beings will learn from the tragedy.`],
    ["The Tiefling Purge:", `The Tiefling Purge of 164, was the largest genocide of a single race in the fifth age. Tensions between the humans and elves with the Tieflings, had been building for many centuries, ever since the city was founded. Tieflings are the offspring of breeding between demons and humans from many ages ago. They are commonly believed by most of the realm to be a curse on the world, and a way for the devils and monsters of Lalotai to corrupt and destroy our world.
    At the beginning of the 160’s when a new group of nobles took charge of the Cirrus, a mass collective of Kylvorans started believing in the xenophobic claims of many of the charismatic nobles, leading to the development of several cult groups, many blaming their problems on the Tiefling populations.
    An uncomfortable peace was intact until the still unexplained case of the ‘emerald explosion’, in which 37 humans, elves, and gnomes were killed, in an unknown green energy explosion caused in the residential section of the eastern side of Kylvoro. The noble human leader of Kylvoro, Jahrn Raskopoulos, called for the need of ‘a cleansing purge of the demon-spawn Tieflings’, blaming them for the tragedy among many other claims.
    The moderate population of Tieflings already lived outside of the city walls mostly by themselves only coming into the city for work and trade, due to being ignored and outcast by the Kylvorans. A week after the ‘emerald explosion’ a large mob of people from the entire range of the city’s population torched and destroyed the homes of the Tiefling communities and killed or imprisoned an estimated 95% of all Tieflings in Kylvoro, with few escaping with their lives.
    Upon learning of the massacre King Roald rode out all the way to Kylvoro from Vvardenrock with his personal elite guard. When he arrived he summoned all the citizens of Kylvoro to the city centre, where there is a statue dedicated in his honour. He vividly described his outrage and then whilst his guards restrained Jahrn Raskopoulos the King personally executed Raskopoulos in front of the Kylvoran people. Roald highly condemned the purge and warned that nothing of this nature is tolerable in his kingdom before having the other conspiring nobles tried and imprisoned for their crimes. To this day, many of the heads of now-dismantled noble houses rot in the brig cells of the Cirrus.`],
    ["Political System:", `Kylvoro is run by a small group of elected officials, who govern in a small palatial building on the side of the Yama mountain overlooking Kylvoro called the Cirrus. Throughout history this has almost always been high-elves, half-elves, and humans, with exception of Deloris Snulin, a fortunate gnome who held her position for almost her entire career until the late 150s. The original leaders used to be the native and peaceful Tieflings, who initially founded small colonies surrounding the Yama mountain, before the king set up a political outpost in the area with the promise of residence for them.
    Kylvoro is governed by ‘The Leader’ who is the overseer of all policy and decisions. Most of the work is carried out by the three advisory leaders, one governing the treasury and commerce, one for defence and infrastructure, and the other Health, Human Services and Justice. These three are responsible for the general running of the city and are capable of the majority of change, if approved by The Leader. There are then seven cirrus council members who are responsible for carrying out and implementing all Cirrus policy as dictated to them from the above.
    Each level of responsibility has an odd number of positions to result in there never being a tie. The Leader has the power to overrule a lost decision provided that there isn’t a valid reason The Leader is unfit for the responsibility, or the policy was 100% rejected by everyone else but The Leader.
    Every politician in the cirrus lives within it’s walls and wear a long crimson gown with a golden embroidered cloudy mountain on the heart, on top of and only partially obscuring their expensive lavish clothes. They regularly mingle in the city accompanied by a personally assigned Mistguard, except for the Leader who would rarely be seen besides public event situations and celebration festivals.`],
  ],
  population: "~ 1250 (50% human, 26% elf, 8% half-elf, 8% dwarf, 6% gnome, 2% other races)",
};
