import { Location } from "../../../../@types/Location/Location";
import { DataTypeIds } from "../../../../Constants/Ids/DataTypeIds";
import { LocationIds } from "../../../../Constants/Ids/LocationIds";
import { NpcIds } from "../../../../Constants/Ids/NpcIds";
import { dataItemToLinkable } from "../../../../Utilities/LinkableString";

export const Menzoberranzan: Location = {
  id: LocationIds.Menzoberranzan,
  type: DataTypeIds.Location,
  description: [
    `Menzoberranzan, also known as the City of Spiders, was a large underground elvish city-state, located under the ${dataItemToLinkable(DataTypeIds.Location, LocationIds.ArgurrosMountains)} on the ${dataItemToLinkable(DataTypeIds.Location, LocationIds.CryingIsland)}.
    Menzoberranzan was one of the few drow cities on the continent of ${dataItemToLinkable(DataTypeIds.Location, LocationIds.Icaros)}. Menzoberranzan was located in a huge arrowhead-shaped cavern, some four miles wide and two thousand feet high.
    The drow called the cavern Araurilcaurak, the drow (undercommon) word for "Piercing place", after its pointed shape.
    The city was mainly carved from calcite and it was filled with blue, green, and violet faerie fire.
    Buildings were often covered with the city's main motif: the spider, in honor of the large amount of spiders that existed in the cave before and continue to coexist with the city's inhabitants.
    The roof of Menzoberranzan was covered in paths. Many homes owned by upper class members of the city were 500-1,000 feet above the floor. Ceiling houses had to have great magic to prevent them from falling, and in the city, the height of your house was a symbol of status.
    An enchantment in the city cavern reduced echos from all the noise, making the city seem significantly smaller than it actually was, as well as being louder than many people expected.
    There were a fixed number of buildings in Menzoberrazan, meaning that the poorer areas were extremely crowded.
    Noble houses, once destroyed or abandoned, were not permitted to be reoccupied until a certain amount of time had passed, meaning that there were a number of abandoned compounds both on the surface and roof of the city cavern.
    The city had around a hundred gates, all guarded. These gates led into the myriad tunnels surrounding the city (collectively called the Bauthwaf, meaning "around cloak").
    The city was divided into a number of distinct areas - the highest tier, known as Tier Breche, the noble tier, known as Qu'ellarz'orl, and the Mantle, which housed the lower status and less important parts of the city. Only drow were allowed to own housing that was not in the Mantle.`,
    `One of the most distinct structures in the city was the huge obisian pillar-clock called The Narbondel. It was enchanted each morning by the Archmage of Menzoberranzan with a glow that slowly dissipated as the day wore on.
    The Narbondel could be seen from throughout the entire city. When the pillar was completely dark, it was called Narbondel's Black Death (effectively midnight). This was a time of celebration within the city, with many of the city dwellers being nocturnal.
    Besides being the clock of Menzoberranzan, within the stalagmite, was the tomb of the legendary founder of the city itself, Menzoberra the Kinless. From the top of the pillar, stairs lead to the hidden chamber where the body of the priestess once lay in a cocoon upon a huge spider's web spanning a tremendous abyss.
    The tomb was originally uncovered by the then-head of house Do'Urden, a minor noble house, Ma'liss Do'Urden. The uncovering of the secret staircase in late 4e 700 eventually propelled house Do'Urden into very high status, with it being one of the most powerful houses in the city for centuries after this.
    When Ma'liss took the Dagger of Menzoberra, the spider's web crashed and the cocoon with the corpse fell into the depths. Many saw this as an omen of destruction, but after centuries of little issue, it's often spouted as the tale of a crazy person instead.
    The tomb can be visited from the hours of Midnight until sunrise, by anyone in the city, and holds a number of statues of the Elvish pantheon, as well as the Raven Queen. The tomb also holds the body of Menzoberra, and the Dagger of Menzoberra is on display behind a locked glass case and is guarded by city watch round the clock.`,
    "Death (usually by intrigue) was widespread in Menzoberranzan. The dead were usually placed in airtight stone crypts in the solid rock north of the city cavern so that they could later be reanimated as battle fodder. Only priestesses were cremated to prevent such a thing occurring to their corpses.",
    ["Founding of the City:", `The city was founded at some point during the first age, although did not rise to its current prominence or population until the third age, when many elves fled underground to escape the Ustaquelet ('Day of Burnt Corpses' in elvish), a cataclysmic event of green fire that ravaged the planet.
    the city was founded by Menzoberra the Kinless, a powerful priestess of Elistraee, founded the city that bears her name. By the wishes of Lady Elistraee, the Drow Goddess, she led seven drow families into the Northdark from the city of H'raclos. Menzoberra never had any descendants or siblings, leading some to believe she was actually an incarnation of Elistraee or even Selemene.
    The original seven drow families, having no immediate external enemy, fell to attacking and undermining one another — exactly what they had hoped to escape in the then war-torn city of H'raclos. Only fifty years after the city's founding, a great and terrible battle between the two most powerful Houses, House Nasadra and House Thaeyalla, occurred.
    This battle led to the collapse of a cavern wall that destroyed many buildings and killed Menzoberra. The perpetrators, House Nasadra, were attacked by House S'sril and House Baenre chose to side with them against Nasadra. House Nasadra were banished from the cave, leading to the drow coining the insult 'Ched Nasad', 'Stupid Traitor' in undercommon.
    After the banishment of house Nasad, House Baenre then rose as the First House of Menzoberranzan, where it has held the title since.`],
    "The city's internal machinations continued unabated for millennia. The Houses that grow weak were destroyed, and newer Houses rose up to find favor. The full history of each House would constitute a nearly endless logbook of treachery, spite, and unceasing ambition. House Baerne stood as the first house for the whole of the city's history, even with the other houses constantly warring with each other.",
    ["Trade:", `The city exported poisons, mushrooms, riding lizards, spell scrolls, wine, and water (clean water could be hard to come by in the Underdark, and often had to be created or purified by clerics).
    Other goods included body dyes, chains, everdark ink, giant slugs, herbal medicines, zurkhwood kayaks and other items, musical instruments (flutes, drums), stone sculptures, surgical services, textiles, tortoiseshell goods, and ulaver wine, as well as a number of magical exports. The city also imported and exported slaves - often they were creatures that were captured in the underdark, or creatures that had broken the law.
    The items were often shipped to the elvish port town of ${dataItemToLinkable(DataTypeIds.Location, LocationIds.Hraclos)} for transport to the main continent, or sold within the Crying islands.`],
    ["Political Structure:", `The city had many different factions, or Houses, all of which vied for power. Officially, the city was under the rule of the Ruling Council of Eight, composed of the eight matron mothers of the first (and most powerful) eight houses.
    For eleven centuries, it was under the indirect rule of House Baenre which was governed by Matron Mother Yvonnel Baenre, also known as Old Matron Baenre, perhaps the most powerful de facto ruler the city ever saw.
    House Baenre had been the First House of Menzoberrazan for centuries of uncontested power. Yvonnel eventually died in the early 5th age, and ${dataItemToLinkable(DataTypeIds.Npc, NpcIds.QuenthelBaenre)} took over her position as head of house Baerne and also as the Matron Mistress of Arach-Tinilith.`],
    ["City Defenses:", "City guard, called Driderguard, often ride around the city attached to living giant spiders via a special saddle that makes them look akin to driders, although they are significantly less evil. Each driderguard was charged with caring for their own spider, and were given special quarters in Qu'ellarz'orl. Killing smaller spiders in view of a guard would result in a fine, and killing a giant spider (even unintentionally) was punishable by death by the law of the City."],
    ["The Academy:", `The Academy of Menzoberranzan was located in Tier Breche and was composed of three schools: Arach-Tinilith, the clerical school; Sorcere, the wizards' school; and Melee-Magthere, the warriors' school.
    Tier Breche was technically the name of the cavern where the Academy was located, but in common usage "Tier Breche" often referred to the Academy itself. The area that housed the schools a small side cavern off the main city cavern and consisted of the highest point in the city of Menzoberranzan. Additionally, two large spider statues could be animated to protect the Academy. It housed the three school complexes, which were carved from stalagmites and rock. Melee-Magthere, shaped like a pyramid, was located in the east. Sorcere, a many-spired tower, was located near the western wall.
    Arach-Tinilith, a spider-shaped complex and the largest of the three schools, both in terms of physical and numerical size, was located at the north of the cavern. A large staircase connected Tier Breche with the main city cavern. Two sentries, generally former students of Melee-Magthere, stood guard at the twin pillars.
    There were magical wards around Tier Breche that were designed to keep out unfriendly spirits; when breached, the wards sounded a loud alarm.`],
    ["The Archmage of Menzoberranzan:", `The Archmage of Menzoberranzan was a title for the head of Sorcere in the fabled drow city. Their role was to advise and serve the ruling Council, especially in devising magics for the defense of the city, and to help the inhabitants of the city keep track of time in the lightless Underdark by casting a lingering heat enchantment on Narbondel. This duty, incidentally, kept them tied to the city and under the watchful eye of its priestesses. The current archmage was ${dataItemToLinkable(DataTypeIds.Npc, NpcIds.GromphBaerne)}`],
    ["Food and drink:", `Local food was primarily produced in and around Lake Donigarten, the large freshwater lake that lied in the Mantle. The Isle of Rothe in the lake housed the city's rothe herds, managed by House Hunzrin, which provided rothe cheese and meat to the city. The area in and around Donigarten also housed moss fields, giant mushrooms, fungus farms, fish, and slaves.
    Pyrimo, a type of aggressive fish similar to piranhas, was prized, despite being deadly if not prepared in the correct manner. Cheap street food in Menzoberranzan included sausage and rolls, which could be bought from street vendors in the Braeryn slum, and pickled sausage. Finer foods included rothe steak, raw mushrooms with creamy dipping sauces, wine, and a salad of black, red, and white fungus.
    Alcoholic beverages found in Menzoberranzan included green ulaver wine and a sweet, light amber colored dessert wine. There was also lace fungus brandy that many in the city enjoyed.`],
    ["Entertainment:", `Entertainment was perhaps not the most obvious word connected with Menzoberranzan, but the city nevertheless provided recreation and relaxation (as much as possible) to its (drow) inhabitants. Taverns were plentiful and brothels could be found if one looked hard enough. The Bazaar offered food, shopping, street performers, and even a game tent or two. Massage parlors, gambling and fighting pits, and public bath houses, all of which were usually manned by slaves, offered their services.
    Sava was a popular chess-like game that represented war between noble houses. It was often played in taverns. Another notable past time in Menzoberranzan was the plotting and carrying out of pranks.
    By law, parties had to end at start of new day (the Black Death of Narbondel, or midnight). Dancing while armed was considered an insult (as well as being hazardous), so dances, particularly the frenzied 'nedeira', were usually performed sans clothing.`],
    `Though no laws or dictates govern it, a drow that enters one of these to enjoy themselves (not merely running from a fight) is considered to be immune to attack or assassination.  As these times (and places) are those in which drow are the most vulnerable in public the safety of these sites is protected by unspoken agreement of the noble houses (who know there's always a way to get at someone even at those times when they are watchful).  Since this is governed only by custom and the threat of reprisal, those who run these establishments always keep magical wards and guards around to ensure this safety is not violated.
    As well, even members of rival houses and those personal feuding with each other will join forces to attack anyone violating this peace, even if they themselves aren't threatened.`,
    ["Noble Houses of Menzoberranzan:", "The main noble houses of Menzoberranzan were (in order of power): Baerne, Del'Armgo, Tlabar, Xorlarrin, Mizzrym, Fey-Branche, Mel'Arn, Do'Urden. The head of each house performed a different function for the city, and these functions changed as the heads of houses evolved over time. A number of smaller noble houses existed, but were not as important to the funcitoning of the city and held little sway in the decisions of the city."],
    ["Branding:", `Whether by actual branding with a scaldingly hot iron, using tattoos, using magic (such as wizard mark or the more common and less permanent color cantrip), or some other method, branding would seem to be common in a city with prestigious, vying noble houses, innumerable slaves and servants, and pets and mounts.
    The truth is surprising.  Since most marks are permanent and most slaves and mounts may not be kept permanently (even by lower houses), most of the city's slave owners prefer not to mark their property and destroy their resale value.  This is also limited by the prohibitions against non-nobles openly using symbols in the city (even the mercenary companies stick to certain modes of dress without unit symbols unless in the current employ of a house).
    Those who do choose to use symbols on their property usually do so in the form of tabards, collars, or something else that can be removed when the property is sold.  There is one exception to this.  Property belonging to the church of Elistraee (not an individual house or priestess) can never be sold and is always prominently and permanently marked with her symbol (often highlighted in continual faerie fire).  This even includes the golems, jade spiders, and other automatons that might be found defending a temple as well as slaves and pets. Sometimes drow soldiers of the temples are also branded (usually on their cheek) in this fashion--a process that requires a regenerate spell to heal.
    One other method of branding that has arisen among the lower noble houses in the last decade or two and is coming into vogue is the tattooing of all house nobles (usually on the back so it can be concealed easily) with the house's insignia.  Magical inks that glow in the visible, ultraviolet, and infrared spectrums are usually used.   This is meant to ensure nobles are absolutely loyal to their house as they will have nowhere to run if the house falls.
    Others have pointed out this also makes them easy to locate with magic and scry on.`],
    ["Greetings:", `Most humanoids aren't interested in elaborate greetings and drow know only too well how salutes and shaking hands can even be turned into an attack (such as releasing a spell, activating an item, spreading dust, or delivering a contact poison) so they don't bother with them. The most common methods of greeting are to cross clenched fists over the chest (crossed at mid forearm or wrist), hold shield in front of chest and fist or weapon against it in front of it, or a firm clasping of each other's forearm (possibly both in the case of close friends or allies).
    Any display of weapons skill, magic (even a cantrip as long as it proves one is a spellcaster), or powerful force (such as a large unit of troops) but then keeping hands away from weapons, keeping fingers interlocked to prevent quick spellcasting, or keep troops with their arms at "attention" is considered a sign of intended peaceful dialogue.  Closing formation (or simply moving) to one side of a cavern, cave, or passage, indicates intent to allow another group to pass or to share the area (possibly passing each other by at the same time).  Drawing weapons or preparing spellcasting but then moving away while warily watching indicates a lack of trust along with a lack of desire for conflict (a common way to act toward groups of drow encountered in the Underdark).`],
    ["City rules:", `Generating dancing lights is acceptable at any time but tradition prevents the use of the "fiery humanoid" form under any circumstances other than battle.  Likewise, using faerie fire is acceptable as long as it's not actually used on a person, their slave, or their mount.  So it could be generated on a rock to light an area but coating someone in it is considered an attack (especially since it usually preceeds an attack).  This has led to some interesting practices, however.
    Sometimes drow (usually nobles) will decide to coat someone weaker than them (usually a non-drow since one can never tell when a drow beggar is actually an archmage) just to see them run away (giving bystanders a great deal of amusement).
    Since someone running through the streets covered in faerie fire is presumed to be fleeing a fight (and thus with enemies in hot pursuit) sometimes drow will coat themselves with faerie fire in hopes that people will avoid them in an attempt not be caught under trampling lizard hooves or by a fireball.
    This is a dangerous ploy just to keep the streets clear ahead of you, however, as there are many opportunists who see the chance to do a favor for an obviously more powerful drow.   Using darkness on someone is considered an attack, even if it is merely placed so the user is caught in its area of effect but covering a light source with it, as long as no one is caught in it (or their mount or slave) is acceptable.
    Hitting anyone with a dispel magic is considered an attack (as it might affect personal defenses, potions, etc.) but affecting something they are doing and not them (for example, dispelling a levitation on a rock) is merely considered a warning and show of power.  The use of suggestion is only acceptable if it comes form a noble or a priestess.
    Of course, it can always be used on one's own slaves or commoners of other races. Any other use, however, is an attack. Torches may be carried but not placed permenantly on a surface such as in a torch scabbard, and all torches must be non-magical in nature unless required by work or given by special permit.
    Poisoning or contaminating any source of water (including deliberately introducing dangerous creatures) except small handheld sources such as cups or glasses is punishable by immediate death. This includes barrels of water or wine. Water is one of the life bloods of the underdark (the other is air) and so endangering the entire environment is a danger to all. Poisoning a kill or food is perfectly acceptable and is a common tactic used with bait, and a way of noble houses to get rid of people that may be against them.`],
  ],
  population: "~ 22,000 (72% drow, 17% other elf, 4% half-elf, 4% orc, 3% other races)",
};
